spring:
  datasource:
    url: jdbc:postgresql://192.168.1.45:5432/ait_wcs_new?sslmode=disable&blobMode=off&options=-c%20TimeZone=Asia/Shanghai
    username: aitplus
    password: aitplus@1234
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 多久检查一次连接的活性
      keepaliveTime: 30000
      maximum-pool-size: 20
      minimum-idle: 10
  redis:
    host: 192.168.1.45
    port: 6379
    password: 123456
    database: 15
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 2
        max-wait: 5000ms
